# Install pre-commit hooks via
# pre-commit install

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: ef4a397f916211b4a39ccf9d3d9cbb6562157251 # frozen: v3.9.9
    hooks:
      - id: prettier
        files: \.(css|html|md|yml|yaml|toml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f12be1ebaa5351c1fc76472de98db2c3446c8253 # frozen: v0.16.10
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: dda8db18cfc68df532abf33b185ecd12d5b7b326 # frozen: 1.20.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 2834ec6639549dd6796205c8f011dedcd587288b # frozen: v2.4.0
    hooks:
      - id: mypy
        exclude: |
          (?x)(
            ^example_pkg_src/
          )

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: fa412071e4f5d44d44f9e365f4676f9df92456a2 # frozen: v1.30.1
    hooks:
      # Run the linter.
      - id: zizmor
        args: [--no-progress, --fix]

  - repo: https://github.com/codespell-project/codespell
    rev: "57b21406f092110c18776e39b0bda50d37c945c8" # frozen: v2.4.3
    hooks:
      - id: codespell
        args: ["-L", "ans"]

  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: "02e248af5abb8e1722b77642c58c4abbf93703dd" # frozen: 0.1.3
    hooks:
      - id: markdown-toc-creator
        files: README.md
        args:
          [
            "--skip-first-n-lines=4",
            "--add-toc-title=false",
            "--add-horizontal-rules=false",
          ]
