# Install pre-commit hooks via
# pre-commit install

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: c2bc67fe8f8f549cc489e00ba8b45aa18ee713b1  # frozen: v3.8.1
    hooks:
      - id: prettier
        files: \.(css|html|md|yml|yaml|toml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c60c980e561ed3e73101667fe8365c609d19a438  # frozen: v0.15.9
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: dda8db18cfc68df532abf33b185ecd12d5b7b326 # frozen: 1.20.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 8e5c80792e2ec0c87804d8ef915bf35e2caea6da  # frozen: v1.20.0
    hooks:
      - id: mypy
        exclude: |
          (?x)(
            ^example_pkg_src/
          )

  - repo: https://github.com/codespell-project/codespell
    rev: "2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a"  # frozen: v2.4.2
    hooks:
      - id: codespell
        args: ["-L", "ans"]

  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: "02e248af5abb8e1722b77642c58c4abbf93703dd" # frozen: 0.1.3
    hooks:
      - id: markdown-toc-creator
        files: README.md
        args:
          [
            "--skip-first-n-lines=4",
            "--add-toc-title=false",
            "--add-horizontal-rules=false",
          ]
